eventapp/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blogslist, name="blogslist"),
    path("create/", views.create_blog, name="create-blog"),
    path("<slug>/", views.blog_detail, name="blog-detail"),
    path("<slug>/edit/", views.edit_blog, name="edit-blog"),
    path("<slug>/delete/", views.delete_blog, name="delete-blog"),
]

eventapp/committee/urls.py
from django.urls import path
from . import views

app_name = "committee"

urlpatterns = [
    path('', views.committeelist, name="committee"),
    path("<slug>/", views.detail_committee_view, name="committee-detail"),
    path("<slug>/edit/", views.edit_committee_view, name="edit-committee"),
]

eventapp/eventapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('committee/', include('committee.urls')),
    path('', include('event.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventapp/committee/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.dispatch import receiver


def upload_location(instance, filename, **kwargs):
    file_path = "committee/{author_id}/{name}-{filename}".format(
        author_id=str(instance.author.id), name=str(instance.name), filename=filename
    )
    return file_path


class Committee(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    wallpaper = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="date created")
    link = models.URLField(null=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.name


@receiver(post_delete, sender=Committee)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    instance.wallpaper.delete(False)


def pre_save_commmitee_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)


pre_save.connect(pre_save_commmitee_post_receiver, sender=Committee)

eventapp/committee/forms.py
from django import forms
from committee.models import Committee


class UpdateCommitteeForm(forms.ModelForm):
    class Meta:
        model = Committee
        fields = ["name", "description", "image", "wallpaper", "link"]

    def save(self, commit=True):
        committee = self.instance
        committee.name = self.cleaned_data["name"]
        committee.description = self.cleaned_data["description"]
        committee.link = self.cleaned_data["link"]

        if self.cleaned_data["image"]:
            committee.image = self.cleaned_data["image"]

        if self.cleaned_data["wallpaper"]:
            committee.image = self.cleaned_data["wallpaper"]

        if commit:
            committee.save()
        return committee

eventapp/committee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger

from .models import  Committee
from .filters import CommitteeFilter
from .forms import  UpdateCommitteeForm
from event.models import EventPost, EventCategory
from event.filters import EventFilter

POST_PER_PAGE = 5
# List of All blogs

def committeelist(request):
    context = {}
    
    committee = Committee.objects.all().order_by('date_updated').reverse()

    myFilter = CommitteeFilter(request.GET, queryset=committee)
    committee = myFilter.qs

    context['committee'] = committee

    return render(request, 'committee/committee_home.html', context)

def detail_committee_view(request, slug):
    context = {}

    committee = get_object_or_404(Committee, slug=slug)
    context["committee"] = committee

    categories = EventCategory.objects.all()
    event_posts = EventPost.objects.filter(author=committee.author)
    myFilter = EventFilter(request.GET, queryset=event_posts)
    events = myFilter.qs

    # Pagination
    page = request.GET.get("page", 1)
    event_posts_paginator = Paginator(event_posts, POST_PER_PAGE)

    try:
        event_posts = event_posts_paginator.page(page)
    except PageNotAnInteger:
        event_posts = event_posts_paginator.page(POST_PER_PAGE)
    except EmptyPage:
        event_posts = event_posts_paginator.page(event_posts_paginator.num_pages)

    context['event_posts'] = event_posts
    context['categories'] = categories

    return render(request, "committee/detail_committee.html", context)

def edit_committee_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")

    committee = get_object_or_404(Committee, slug=slug)

    if committee.author != user:
        return HttpResponse("You are not the author of that post.")

    if request.POST:
        form = UpdateCommitteeForm(
            request.POST or None, request.FILES or None, instance=committee
        )
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            messages.success(request, f"Update successfull!")
            committee = obj
            return redirect("../../{}/".format(committee.slug))

    form = UpdateCommitteeForm(
        initial={
            "name": committee.name,
            "description": committee.description,
            "link": committee.link,
            "image": committee.image,
            # "back_image": committee.back_image,
        }
    )

    context["form"] = form
    return render(request, "committee/edit_committee.html", context)

eventapp/committee/templates/committee/committee_home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
    @media (max-width: 768px) {
        .left-column {
            margin-right: 0px;
        }
    }

    @media (min-width: 768px) {
        .left-column {
            margin-right: 10px;
        }
    }

    .create-post-bar {
        background-color: #fff;
        margin-bottom: 20px;
    }

    .card {
        max-width: 700px;
    }

    .container {
        padding: 20px;
    }

    .lead {
        font-size: 17px;
    }

    .xop-grid li {
        width: 328px;
        height: 328px;
        display: inline-block;
        margin: 20px;
        position: relative;
    }

    .xop-box {
        width: 100%;
        height: 100%;
        position: relative;
        cursor: pointer;
        border-radius: 10px;
        -webkit-transition: 0.3s ease-in-out,
            -webkit-transform 0.3s ease-in-out;
        -moz-transition: 0.3s ease-in-out,
            -moz-transform 0.3s ease-in-out;
        transition: all 0.3s ease-in-out,
            transform 0.3s ease-in-out, ;
    }

    .xop-box:hover {
        transform: scale(1.05);
    }

    .text {
        font-size: 35px;
        text-align: center;
        color: #00BFFF;
        animation: blink 1s steps(5, start) infinite;
    }

    @keyframes blink {
        to {
            color: #4169E1;
        }
    }
</style>
<div class="text">
    <p><b>List of PCE Student Committee</b></p>
</div>
<div class="m-auto xop-section" style="max-width: 1200px;">
    <ul class="xop-grid">
        {% if committee %}
        {% for post in committee %}
        <li>
            <div class="committee-post-container">
                <div class="xop-box">
                    {% include 'committee/snippets/committee_snippet.html' with committee=post %}
                </div>
            </div>
        </li>
        {% endfor %}
        {% else %}
        <div class="committee-post-container">
            {% include 'committee/snippets/committee_snippet.html' with query=query %}
        </div>
        {% endif %}

        <!-- End Event posts-->
    </ul>
</div>


{% endblock content %}

eventapp/committee/templates/committee/detail_committee.html
{% extends 'base.html' %}
{% block content %}

<style type="text/css">
    @media (max-width: 768px) {
        .left-column {
            margin-right: 0px;
        }
    }

    @media (min-width: 768px) {
        .left-column {
            margin-right: 10px;
        }
    }

    .create-post-bar {
        background-color: #fff;
        margin-bottom: 20px;
    }

    .card {
        max-width: 700px;
    }

    .container {
        padding: 20px;
    }

    .flex-container {
        display: flex;
    }

    .lead {
        font-size: 17px;
    }

    #fly {
        position: absolute;
        opacity: 0;
        animation: flyIn 1s ease 1.5s 1 forwards;
    }

    @keyframes flyIn {
        0% {
            height: 0px;
            width: 200px;
            margin: 0px 0px 0px 50px;
            opacity: 1;
        }

        100% {
            margin-bottom: 20px;
            height: 350px;
            width: 200px;
            margin: 0px 0px 0px 50px;
            opacity: 1;
        }
    }

    div.sticky {
        position: -webkit-sticky;
        /* Safari */
        position: sticky;
        top: 0;
    }

    #filters {
        margin-left: auto;
        margin-bottom: auto;
        margin-top: 20px;
        min-width: 200px;
    }
</style>
<div class="flex-container">
    <div class="container">
        <div class="row">

            <!--committee-->
            <div class="card m-auto">
                <img class="card-img-top" src="{{committee.image.url}}" alt="{{committee.image.url}}">
                <div class="card-description my-2 mx-2">
                    <h2 class="card-name">{{committee.name}}</h2>
                    <pre class="card-text">{{committee.description|safe}}</pre>
                    <p class="lead-bold">Official Site: <a href="{{committee.link}}"
                            target="_blank">{{committee.link}}</a>
                    </p>
                </div>
                <div class="card-footer text-muted">
                    Updated on {{committee.date_updated}} by {{committee.author.username}}
                </div>
            </div>
            <!--End committee Post-->

            <div class="left-column col-lg-3 d-lg-flex d-none flex-column">

                <div class="card create-post-bar d-flex flex-column p-3 shadow-lg" id="fly">
                    <img class="img-fluid d-block m-auto pb-2" src="{{committee.image.url}}" width="80" height="80">
                    <p class="lead">This Page contains information regarding {{committee.name}} and its recent events.
                    </p>
                    <p class="lead-bold">Current Handler:
                        {{committee.author.username}}</p>
                    {% if committee.author == request.user %}
                    <a href="{% url 'committee:edit-committee' committee.slug %}" class="btn btn-primary">Update</a>
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="container mx-0 mt-4 p-4">
            <div class="row">
                <div class="blog-posts">
                    <h3 class="mx-auto mb-3 font-weight-normal">Active Events</h3>
                    {% if event_posts %}
                    {% for post in event_posts %}
                    <div class="event-post-container">
                        {% include 'event/snippets/event_card.html' with event_post=post %}
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="event-post-container">
                        {% include 'event/snippets/event_card.html' with query=query %}
                    </div>
                    {% endif %}
                    <!-- End Event posts-->
                    <!-- Pagination -->
                    {% include 'event/snippets/event_post_pagination.html' with event_posts=event_posts %}
                </div>
            </div>
        </div>
        <div class="">
            <p class="lead-bold">For older events please visit the official site: <a href="{{committee.link}}"
                    target="_blank">{{committee.link}}</a></p>
        </div>

    </div>
</div>


{% endblock content %}

eventapp/committee/templates/committee/edit_committee.html
{% extends 'base.html' %}
{% block content %}

<style type="text/css">
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}

	.submit-button {
		max-width: 200px;
	}

	.image {
		opacity: 1;
		transition: .5s ease;
		backface-visibility: hidden;
	}

	.middle {
		transition: .5s ease;
		opacity: 0;
		position: absolute;
		text-align: center;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}

	.image-group {
		position: relative;
		text-align: center;
		cursor: pointer;
	}

	.image-group:hover .image {
		opacity: 0.3;
	}

	.image-group:hover .middle {
		opacity: 1;
	}

	.text {
		margin: auto;
		background-color: #33ccff;
		color: white;
		font-size: 15px;
		padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- name -->
				<div class="form-group">
					<label for="id_name">Name</label>
					<input class="form-control" type="text" name="name" id="id_name" placeholder="Name"
						value="{{form.initial.name}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_description">Content</label>
					<textarea class="form-control" rows="10" type="text" name="description" id="id_description"
						placeholder="This committee is about..." required>{{form.initial.description}}</textarea>
				</div>

				<!-- link -->
				<div class="form-group">
					<label for="id_link">Site</label>
					<input class="form-control" type="url" name="link" id="id_link" placeholder="Link"
						value="{{form.initial.link}}">
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					<div class="middle">
						<div class="text">Change image</div>
					</div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">

				<!-- Background Image
                <div class="form-group image-group" id="id_image_group">
                    <img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
                      <div class="middle">
                        <div class="text">Change image</div>
                      </div>
                </div>
                <input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">-->



				{% for field in form %}
				<p>
					{% for error in field.errors %}
				<p style="color: red;">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if form.non_field_errors %}
				<div style="color: red">
					<p>{{form.non_field_errors}}</p>
				</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function (event) {
		document.getElementById('id_image_file').click();
	};

	function readURL(input) {
		var reader = new FileReader();
		reader.onload = function (e) {
			$('#id_image_display')
				.attr('src', e.target.result)
		};
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}