eventapp/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blogslist, name="blogslist"),
    path("create/", views.create_blog, name="create-blog"),
    path("<slug>/", views.blog_detail, name="blog-detail"),
    path("<slug>/edit/", views.edit_blog, name="edit-blog"),
    path("<slug>/delete/", views.delete_blog, name="delete-blog"),
]

eventapp/event/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.eventlist, name="eventslist"),
    path("create/", views.create_event, name="create-event"),
    path("<slug>/", views.event_detail, name="event-detail"),
    path("<slug>/edit/", views.edit_event, name="edit-event"),
    path("<slug>/delete/", views.delete_event, name="delete-event"),
]

eventapp/eventapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('committee/', include('committee.urls')),
    path('', include('event.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventapp/event/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.dispatch import receiver

def upload_location(instance, filename, **kwargs):
    file_path = "event/{author_id}/{title}-{filename}".format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path

class EventCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class EventPost(models.Model):

    CATERGORY_CHOICES = []
    for event_category in EventCategory.objects.all():
        CATERGORY_CHOICES.append((str(event_category.name), str(event_category.name)))
    
    title = models.CharField(max_length=100, null=False, blank=False)
    body = models.TextField(max_length=1200, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    category = models.CharField(max_length=100, choices=CATERGORY_CHOICES, default="null")
    event_date = models.DateField(auto_now_add=False, null=False, blank=False)
    reg_to = models.DateField(auto_now_add=False, null=False, blank=False)
    fee = models.PositiveIntegerField(default=0)
    reg_link = models.URLField(null=False, blank=False)
    date_published = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)
    priority = models.IntegerField(default=0)
    day_rem = models.IntegerField(default=0)


    def __str__(self):
        return self.title

@receiver(post_delete, sender=EventPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_event_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)


pre_save.connect(pre_save_event_post_receiver, sender=EventPost)

eventapp/event/forms.py
from django import forms
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from event.models import EventPost, EventCategory
# from account.models import Account


# 1MB - 1048576
# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = "1048576"

CATERGORY_CHOICES = []
for category in EventCategory.objects.all():
    CATERGORY_CHOICES.append((str(category.name), str(category.name)))

class CreateEventPostForm(forms.ModelForm):

    category = forms.ChoiceField(choices=CATERGORY_CHOICES)

    class Meta:
        model = EventPost
        fields = [
            "title",
            "category",
            "body",
            "reg_to",
            "event_date",
            "fee",
            "reg_link",
            "image",
        ]

        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Title.."}
            ),
            "category": forms.Select(attrs={"class": "form-control"}),
            "body": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Content.."}
            ),
            "fee": forms.NumberInput(attrs={"class": "form-control"}),
            "reg_link": forms.URLInput(attrs={"class": "form-control"}),
        }

    def clean(self, *args, **kwargs):
        if self.cleaned_data["image"]:
            self.check_file()
        if self.is_valid:
            if self.cleaned_data["event_date"] < self.cleaned_data["reg_to"]:
                raise forms.ValidationError("Invalid Registration Dates")

    def check_file(self, *args, **kwargs):
        image = self.cleaned_data["image"]
        # content_type = image.content_type.split("/")[0]
        if image.size > int(MAX_UPLOAD_SIZE):
            raise forms.ValidationError(
                _("Please keep image size under %s. Current file size %s")
                % (filesizeformat(MAX_UPLOAD_SIZE), filesizeformat(image.size),)
            )

        return image


class UpdateEventPostForm(forms.ModelForm):

    category = forms.ChoiceField(choices=CATERGORY_CHOICES)

    class Meta:
        model = EventPost
        fields = [
            "title",
            "category",
            "body",
            "reg_to",
            "event_date",
            "fee",
            "reg_link",
            "image",
        ]

        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Title.."}
            ),
            "category": forms.Select(attrs={"class": "form-control"}),
            "body": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Content.."}
            ),
            "fee": forms.NumberInput(attrs={"class": "form-control"}),
            "reg_link": forms.URLInput(attrs={"class": "form-control"}),
        }

    def clean(self, *args, **kwargs):
        if self.cleaned_data["image"]:
            self.check_file()
        if self.is_valid:
            if self.cleaned_data["event_date"] < self.cleaned_data["reg_to"]:
                raise forms.ValidationError("Invalid Dates")

    def check_file(self, *args, **kwargs):
        image = self.cleaned_data["image"]
        # content_type = image.content_type.split("/")[0]
        if image.size > int(MAX_UPLOAD_SIZE):
            raise forms.ValidationError(
                _("Please keep image size under %s. Current file size %s")
                % (filesizeformat(MAX_UPLOAD_SIZE), filesizeformat(image.size),)
            )

        return image

eventapp/event/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from .models import EventPost, EventCategory
from .forms import CreateEventPostForm, UpdateEventPostForm
from .filters import EventFilter
from accounts.models import Profile, PostNum

from datetime import datetime, timedelta


# List of All blogs
limit = PostNum.objects.all().first()
POST_PER_PAGE = limit.blog_limit
# List of All blogs
def eventlist(request):
    context = {}
    
    events = EventPost.objects.all().order_by('date_updated').reverse()
    categories = EventCategory.objects.all()
    now = datetime.today().date()

    fees = []
    for i in EventPost.objects.all():
        if i.fee not in fees:
            fees.append(int(i.fee))

    for event in events:
        day_rem = event.reg_to - now
        EventPost.objects.filter(id=event.id).update(day_rem=day_rem.days)

    myFilter = EventFilter(request.GET, queryset=events)
    events = myFilter.qs

    # Pagination
    page = request.GET.get("page", 1)
    event_posts_paginator = Paginator(events, POST_PER_PAGE)

    try:
        events = event_posts_paginator.page(page)
    except PageNotAnInteger:
        events = event_posts_paginator.page(POST_PER_PAGE)
    except EmptyPage:
        events = event_posts_paginator.page(event_posts_paginator.num_pages)

    context['events'] = events
    context['fees'] = fees
    context['categorys'] = categories

    return render(request, 'event/event_home.html', context)

# Detail of a particular event
def event_detail(request, slug):
    context = {}

    event_post = get_object_or_404(EventPost, slug=slug)
    context['event_post'] = event_post

    return render(request, 'event/event_detail.html', context)

# Create a new event

def create_event(request):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate")
    
    event_posts = EventPost.objects.filter(author=user)
    context["event_posts"] = event_posts
    limit = 0
    for post in event_posts:
        event_date = post.date_published.date()
        today = datetime.now().date()
        if today == event_date:
            limit += 1

    if not user.is_superuser:
        if limit >= user.profile.post_limit:
            return redirect("limit_reached")
    
    form = CreateEventPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = request.user
        obj.author = author
        obj.save()
        messages.success(
            request, f"Your Event has been posted successfully!"
        )
        return redirect("eventslist")

    else:
        form = CreateEventPostForm()
        context["form"] = form
        return render(request, "event/create_event.html", context)


def edit_event(request, slug):

    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect("must_authenticate")

    event_post = get_object_or_404(EventPost, slug=slug)

    # categorys = Category.objects.all()
    # context["categorys"] = categorys
    
    # event_posts = EventPost.objects.filter(author=user)
    # context["event_posts"] = event_posts

    # limit = []
    # edate = blog_post.date_updated.strftime("%Y-%m-%d")
    # edate0 = datetime.strptime(edate, "%Y-%m-%d").date()
    # if today == edate0:
    #     limit.append(edate0)

    # if user.is_staff == 1:
    #     if len(limit) >= user.post_limit:
    #         return redirect("limit_reached")

    if event_post.author != user:
        return HttpResponse("You are not the author of that post.")

    form = UpdateEventPostForm(
        request.POST or None, request.FILES or None, instance=event_post
    )
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, f"Your Post has been updated successfully!")
        blog_post = obj
        return redirect("eventslist")

    form = UpdateEventPostForm(
        initial={
            "title": event_post.title,
            "body": event_post.body,
            "image": event_post.image,
            "category": event_post.category,
            "event_date": event_post.event_date,
            "reg_to": event_post.reg_to,
            "fee": event_post.fee,
            "reg_link": event_post.reg_link,
        }
    )

    context["form"] = form

    return render(request, "event/edit_event.html", context)

def delete_event(request, slug):
    context = {}
    user = request.user

    event_post = get_object_or_404(EventPost, slug=slug)

    if event_post.author != user:
        return HttpResponse("You are not the author of that post.")
    
    if request.method == "POST":
        event_post.delete()
        messages.success(request, f"Your Post has been deleted successfully!")
        return redirect("eventslist")

    context["event_post"] = event_post
    return render(request, "event/delete_event.html", context)

eventapp/event/templates/event/create_event.html
{% extends 'base.html' %}

{% block title %}New Event{% endblock title %}

{% block content %}

<style type="text/css">
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}

	.submit-button {
		max-width: 200px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
				{% include 'snippets/form_errors.html' %}

				<!-- Title -->
				<div>
					<label for="id_title">Title</label>
					<p>{{form.title}}</p>
				</div>

				<!-- Category -->
				<div>
					<label for="id_category">Category</label>
					<p>{{form.category}}</p>
				</div>

				<!-- Content -->
				<div>
					<label for="id_body">Content</label>
					<p>{{form.body}}</p>
				</div>

				<!-- reg_to -->
				<div class="form-check form-check-inline">
					<div class="form-group">
						<label for="id_reg_to">Registration to</label>
						<input class="form-control" type="date" name="reg_to" id="id_reg_to">
					</div>
				</div>

				<!-- event_date -->
				<div class="form-check form-check-inline">
					<div class="form-group">
						<label for="id_event_date">Event Date</label>
						<input class="form-control" type="date" name="event_date" id="id_event_date">
					</div>
				</div>

				<!-- Fee -->
				<div>
					<label for="id_fee">Fee</label>
					<p>{{form.fee}}</p>
				</div>

				<!-- Registration -->
				<div>
					<label for="id_reg_link">Registration link</label>
					<p>{{form.reg_link}}</p>
				</div>

				<!-- Image -->
				<div class="form-group"><br>
					<label for="id_image">Image<span class="text-muted">(size: Less than 1MB)</span></label>
					<input type="file" name="image" id="id_image" accept="image/*" required>
				</div>


				<!-- Submit btn -->
				<button class="submit-button btn btn-lg text-white" style="background-color:#910fff;" type="submit">POST</button>
				<a href="{% url 'eventslist' %}" type="button" class="btn btn-lg btn-danger">CANCEL</a>
			</form>
		</div>
	</div>
</div>
<script>
	var today = new Date().toISOString().split('T')[0];
	document.getElementsByName("reg_to")[0].setAttribute('min', today);

	var today = new Date().toISOString().split('T')[0];
	document.getElementsByName("event_date")[0].setAttribute('min', today);
</script>

{% endblock content %}

eventapp/event/templates/event/delete_event.html
{% extends 'base.html' %}

{% block title %}Delete Event{% endblock title %}

{% block content %}
<div class="content-section bg-white" style="padding: 10px; margin-left: 200px; margin-right: 650px;">
    <form acition="{% url 'event-detail' event_post.id %}" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ event_post.title }}"</h2>
        </fieldset>
        <div class="from-group">
            <button class="btn btn-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-secondary" href="{% url 'event-detail' event_post.slug %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

eventapp/event/templates/event/edit_event.html
{% extends 'base.html' %}

{% block title %}{{event_post.title}}{% endblock title %}

{% block content %}

<style type="text/css">
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}

	.submit-button {
		max-width: 200px;
	}

	.image {
		opacity: 1;
		transition: .5s ease;
		backface-visibility: hidden;
	}

	.middle {
		transition: .5s ease;
		opacity: 0;
		position: absolute;
		text-align: center;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}

	.image-group {
		position: relative;
		text-align: center;
		cursor: pointer;
	}

	.image-group:hover .image {
		opacity: 0.3;
	}

	.image-group:hover .middle {
		opacity: 1;
	}

	.text {
		margin: auto;
		background-color: #33ccff;
		color: white;
		font-size: 15px;
		padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				{% include 'snippets/form_errors.html' %}

				<!-- Title -->
				<div>
					<label for="id_title">Title</label>
					<p>{{form.title}}</p>
				</div>

				<!-- Category -->
				<div>
					<label for="id_category">Category</label>
					<p>{{form.category}}</p>
				</div>

				<!-- Content -->
				<div>
					<label for="id_body">Content</label>
					<p>{{form.body}}</p>
				</div>

				<p class="bold">
					Please Reselect your Dates:
				</p>

				<!-- reg_to -->
				<div class="form-check form-check-inline">
					<div class="form-group">
						<label for="id_reg_to">Registration to:</label>
						<input class="form-control" type="date" name="reg_to" id="id_reg_to" required>
						<span class="text-muted">(Current:{{event_post.reg_to}})</span>
					</div>
				</div>

				<!-- event_date -->
				<div class="form-check form-check-inline">
					<div class="form-group">
						<label for="id_event_date">Event Date:</label>
						<input class="form-control" type="date" name="event_date" id="id_event_date" required>
						<span class="text-muted">(Current: {{event_post.event_date}})</span>
					</div>
				</div>

				<!-- Fee -->
				<div>
					<label for="id_fee">Fee</label>
					<p>{{form.fee}}</p>
				</div>

				<!-- Registration -->
				<div>
					<label for="id_reg_link">Registration link</label>
					<p>{{form.reg_link}}</p>
				</div>


				<!-- Image -->
				<div class="form-group image-group" id="id_image_group"><br>
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					<div class="middle">
						<div class="text">Change image</div>
					</div>
				</div>
				<label for="id_image">Image<span class="text-muted">(size: Less than 1MB)</span></label>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				<hr>

				<!-- Submit btn -->
				<p>
					<button class="submit-button btn text-white" style="background-color:#910fff;" type="submit">Update</button>
				<p><small style="color: red;">Warning: Are you sure you want to change the contents of a Event?
						</smal>
					</small></p>
				</p>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function (event) {
		document.getElementById('id_image_file').click();
	};

	function readURL(input) {
		var reader = new FileReader();
		reader.onload = function (e) {
			$('#id_image_display')
				.attr('src', e.target.result)
		};
		reader.readAsDataURL(input.files[0]);
	}
	var today = new Date().toISOString().split('T')[0];
	document.getElementsByName("reg_to")[0].setAttribute('min', today);

	var today = new Date().toISOString().split('T')[0];
	document.getElementsByName("event_date")[0].setAttribute('min', today);

</script>

{% endblock content %}

eventapp/event/templates/event/event_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{event_post.title}}{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/event-detail.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500&display=swap" rel="stylesheet" />
{% endblock head %}


{% block content %}

<style type="text/css">
    .card {
        max-width: 700px;
    }

    .container {
        padding: 20px;
    }

    pre {
        overflow-x: auto;
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
        white-space: -pre-wrap;
        white-space: -o-pre-wrap;
        word-wrap: break-word;
    }

    .text {
        font-size: 35px;
        text-align: center;
        color: #00BFFF;
        animation: blink 1s steps(5, start) infinite;
    }

    .event-detail-card p {
        font-family: Montserrat, sans-serif;
        font-size: 1.3vw;
    }

    .pts p span {
        font-family: Montserrat, sans-serif;
        font-weight: 500;
    }

    @keyframes blink {
        to {
            color: #4169E1;
        }
    }
</style>

<div class="container">
    <div class="row">

        <!--Event Post-->
        <div class="card m-auto">
        {% if event_post.image.url %}
            <img class="card-img-top" src="{{event_post.image.url}}" alt="{{event_post.image.url}}">
        {% else %}
            <img class="card-img-top" src="{% static 'img/megaphone.png' %}" alt="{{event_post.image.url}}">
        {% endif %}
            <div class="card-body my-2">
                <h2 class="card-title">{{event_post.title}}</h2>
                {% if event_post.author == request.user %}
                <a href="{% url 'edit-event' event_post.slug %}" class="btn text-white" style="background-color:#910fff;">Edit</a>
                <a class="btn btn-danger btn-md mt-1 mb-1" href="{% url 'delete-event' event_post.slug %}">Delete</a>
                {% endif %}
                <hr>
                <div class="pts">
                    <p><span>Event Date</span> : {{event_post.event_date}}</p>
                    <p><span>Last Date of Registration</span> : {{event_post.reg_to}}</p>
                    {% if event_post.fee == 0  %}
                    <p><span>Fee</span> : Free</p>
                    {% else %}
                    <p><span>Fee</span> : {{event_post.fee}}</p>
                    {% endif %}
                    <p><span>Registration link</span> :<a href="{{event_post.reg_link}}" target="_blank">
                            {{event_post.reg_link}}</a></p>
                </div><br>
                <pre class="card-text-bold">{{event_post.body|safe}}</pre>
            </div>
            <div class="card-footer text-muted">
                <b>{{event_post.category}}</b> | Updated on {{event_post.date_updated}}
                by
                <a href="{% url 'author-view' event_post.author.id %}">
                    {{event_post.author.username}}</a>
            </div>
        </div>
        <!--End Event Post-->
    </div>
</div>
{% endblock content %}

eventapp/event/templates/event/event_home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<style type="text/css">
	@media (max-width: 768px) {
		.right-column {
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) {
		.right-column {
			margin-left: 20px;
		}
	}

	.event-post-container {
		margin-bottom: 20px;
		width: 100%;
	}

	.create-post-bar {
		background-color: #fff;
		margin-bottom: 20px;
	}

	.left-column {
		padding: 0px;
	}

	.right-column {
		padding: 0px;
	}

	.lead {
		font-size: 17px;
	}

	/* .filter {
		margin-left: 360px;
		width: 200px;
		height: 80px;
		padding: 5px;
	} */

	#create {
		animation: fadeInAnimation ease 8s;
		animation-iteration-count: 1;
		animation-fill-mode: forwards;
	}

	.flex-container {
		display: flex;
	}

	div.sticky {
		position: -webkit-sticky;
		/* Safari */
		position: sticky;
		top: 60px;
	}

	/* #filters {
		margin-left: auto;
		margin-bottom: auto;
		min-width: 200px;
	} */
</style>

<div class="flex-container">
	<!-- main content -->
	<div class="container">
		<div class="row">
			<!--Top Filters-->
			<div class="col">
				<a style="color:black;" data-toggle="collapse" href="#collapse1">
					<legend><i class="fa fa-filter"></i>Filters</legend>
				</a>
				<div class="panel-collapse collapse" id="collapse1">
					<div class="flex form-group">
						<form method="GET" class="form-inline">

							<!-- event_date -->
							<div class="form-group">
								<input placeholder="Event Date" class="form-control" type="text" name="event_date" id="id_date" onfocus="(this.type='date')" onblur="(this.type='text')">
							</div>

							<!-- reg ends -->
							<div class="form-group">
								<!-- <label for="id_reg_to">Registration Ends</label> -->
								<input class="form-control" type="text" name="reg_to" id="id_reg_to" placeholder="Register unitl" onfocus="(this.type='date')" onblur="(this.type='text')">
							</div>
							
							<!--Category-->
							<div class="form-group">
								<select class="form-control" id="id_category" name="category">
									<option value="">Category</option>
									{% for category in categorys %}
									<option value="{{category.name}}">{{category.name}}</option>
									{% endfor %}
								</select>
							</div>
							
							<!-- fees -->
							<div class="form-group">
								<select class="form-control" id="id_fee" name="fee">
									<option value="">Fees</option>
									{% for fee in fees %}
									{% if fee == 0 %}
									<option value="{{fee}}">Free</option>
									{% else %}
									<option value="{{fee}}">{{fee}}</option>
									{% endif %}
									{% endfor %}
								</select>
							</div>

							<button class="btn text-white mx-2" style="background-color:#910fff;" type="submit">Apply</button>
							<a class="btn btn-primary mx-1" href="{% url 'eventslist' %}">Reset</a>
						</form>
					</div>
				</div>
			</div>
			<!-- event posts-->
			{% if events %}
			{% for post in events %}
			<div class="event-post-container">
				{% include 'event/snippets/event_card.html' with event_post=post %}
			</div>
			{% endfor %}
			{% else %}
			<div class="event-post-container">
				{% include 'event/snippets/event_card.html' with query=query %}
			</div>
			{% endif %}
			<!-- End event posts-->
			<!-- Pagination -->
			{% include 'event/snippets/event_post_pagination.html' with events=events %}

			<!-- end event feed -->
		</div>
	</div>
</div>


{% endblock content %}