eventapp/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blogslist, name="blogslist"),
    path("create/", views.create_blog, name="create-blog"),
    path("<slug>/", views.blog_detail, name="blog-detail"),
    path("<slug>/edit/", views.edit_blog, name="edit-blog"),
    path("<slug>/delete/", views.delete_blog, name="delete-blog"),
]

eventapp/committee/urls.py
from django.urls import path
from . import views

app_name = "committee"

urlpatterns = [
    path('', views.committeelist, name="committee"),
    path("<slug>/", views.detail_committee_view, name="committee-detail"),
    path("<slug>/edit/", views.edit_committee_view, name="edit-committee"),
]

eventapp/eventapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('committee/', include('committee.urls')),
    path('', include('event.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventapp/committee/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.dispatch import receiver


def upload_location(instance, filename, **kwargs):
    file_path = "committee/{author_id}/{name}-{filename}".format(
        author_id=str(instance.author.id), name=str(instance.name), filename=filename
    )
    return file_path


class Committee(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    wallpaper = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="date created")
    link = models.URLField(null=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.name


@receiver(post_delete, sender=Committee)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    instance.wallpaper.delete(False)


def pre_save_commmitee_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)


pre_save.connect(pre_save_commmitee_post_receiver, sender=Committee)

eventapp/committee/forms.py
from django import forms
from committee.models import Committee


class UpdateCommitteeForm(forms.ModelForm):
    class Meta:
        model = Committee
        fields = ["name", "description", "image", "wallpaper", "link"]

    def save(self, commit=True):
        committee = self.instance
        committee.name = self.cleaned_data["name"]
        committee.description = self.cleaned_data["description"]
        committee.link = self.cleaned_data["link"]

        if self.cleaned_data["image"]:
            committee.image = self.cleaned_data["image"]

        if self.cleaned_data["wallpaper"]:
            committee.image = self.cleaned_data["wallpaper"]

        if commit:
            committee.save()
        return committee

eventapp/committee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger

from .models import  Committee
from .filters import CommitteeFilter
from .forms import  UpdateCommitteeForm
from event.models import EventPost, EventCategory
from event.filters import EventFilter

POST_PER_PAGE = 5
# List of All blogs

def committeelist(request):
    context = {}
    
    committee = Committee.objects.all().order_by('date_updated').reverse()

    myFilter = CommitteeFilter(request.GET, queryset=committee)
    committee = myFilter.qs

    context['committee'] = committee

    return render(request, 'committee/committee_home.html', context)

def detail_committee_view(request, slug):
    context = {}

    committee = get_object_or_404(Committee, slug=slug)
    context["committee"] = committee

    categories = EventCategory.objects.all()
    event_posts = EventPost.objects.filter(author=committee.author)
    myFilter = EventFilter(request.GET, queryset=event_posts)
    events = myFilter.qs

    # Pagination
    page = request.GET.get("page", 1)
    event_posts_paginator = Paginator(event_posts, POST_PER_PAGE)

    try:
        event_posts = event_posts_paginator.page(page)
    except PageNotAnInteger:
        event_posts = event_posts_paginator.page(POST_PER_PAGE)
    except EmptyPage:
        event_posts = event_posts_paginator.page(event_posts_paginator.num_pages)

    context['event_posts'] = event_posts
    context['categories'] = categories

    return render(request, "committee/detail_committee.html", context)

def edit_committee_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")

    committee = get_object_or_404(Committee, slug=slug)

    if committee.author != user:
        return HttpResponse("You are not the author of that post.")

    if request.POST:
        form = UpdateCommitteeForm(
            request.POST or None, request.FILES or None, instance=committee
        )
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            messages.success(request, f"Update successfull!")
            committee = obj
            return redirect("../../{}/".format(committee.slug))

    form = UpdateCommitteeForm(
        initial={
            "name": committee.name,
            "description": committee.description,
            "link": committee.link,
            "image": committee.image,
            # "back_image": committee.back_image,
        }
    )

    context["form"] = form
    return render(request, "committee/edit_committee.html", context)

eventapp/committee/templates/committee/snippets/committee_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if committee.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ committee.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in committee.paginator.page_range %}
		{% if committee.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}

    {% if committee.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ committee.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ committee.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

eventapp/committee/templates/committee/snippets/committee_snippet.html
<style type="text/css">
	.card {
		min-width: 320px;
		max-width: 320px;
		width: 100%;
	}

	.card-body {
		padding: 20px;
	}

	.xop-info {
		position: absolute;
		width: inherit;
		height: inherit;
	}

	.xop-info h3 {
		font-family: 'Pacifico', cursive;
		font-weight: 400;
		color: #fff;
		font-size: 42px;
		margin: 0 30px;
		padding: 100px 0 0 0;
		line-height: 1.5;
	}
</style>

{% if committee %}
<div class="xop-box m-auto">
	<a href="{% url 'committee:committee-detail' post.slug %}"><img class="card-img"
			style="object-fit: contain; background: linear-gradient( rgba(0, 0, 0, 0.50), rgba(0, 0, 0, 0.10));"
			src="{{committee.image.url}}"></a>
</div>
{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-name">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}