eventapp/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blogslist, name="blogslist"),
    path("create/", views.create_blog, name="create-blog"),
    path("<slug>/", views.blog_detail, name="blog-detail"),
    path("<slug>/edit/", views.edit_blog, name="edit-blog"),
    path("<slug>/delete/", views.delete_blog, name="delete-blog"),
]

eventapp/committee/urls.py
from django.urls import path
from . import views

app_name = "committee"

urlpatterns = [
    path('', views.committeelist, name="committee"),
    path("<slug>/", views.detail_committee_view, name="committee-detail"),
    path("<slug>/edit/", views.edit_committee_view, name="edit-committee"),
]

eventapp/eventapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('committee/', include('committee.urls')),
    path('', include('event.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventapp/templates/snippets/base_css.html
<style type="text/css">
    body{
        background-color: #f2f2f2;
    }
</style>

eventapp/templates/snippets/footer.html
<style type="text/css">
    * {
        font-family: Montserrat, sans-serif;

        margin: 0;
        padding: 0;
    }

    section {
        width: 100%;
        display: inline-block;
        background: #ccc;
        height: 60vh;
        text-align: center;
        font-size: 22px;
        font-weight: 700;
        text-decoration: underline;
    }

    .footer-distributed {
        background-color: #292c2f;
        box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
        box-sizing: border-box;
        width: 100%;
        text-align: left;
        font: normal 16px sans-serif;
        padding: 45px 50px;
    }

    .footer-distributed .footer-left p {
        color: #8f9296;
        font-size: 14px;
        margin: 0;
    }

    /* Footer links */

    .footer-distributed p.footer-links {
        font-size: 18px;
        font-weight: bold;
        color: #ffffff;
        margin: 0 0 10px;
        padding: 0;
        transition: ease 0.25s;
    }

    .footer-distributed p.footer-links a {
        display: inline-block;
        line-height: 1.8;
        text-decoration: none;
        color: inherit;
        transition: ease 0.25s;
    }

    .footer-distributed .footer-links a:before {
        content: "·";
        font-size: 20px;
        left: 0;
        color: #fff;
        display: inline-block;
        padding-right: 5px;
    }

    .footer-distributed .footer-links .link-1:before {
        content: none;
    }

    .footer-distributed .footer-right {
        float: right;
        margin-top: 0px;
        max-width: 180px;
    }

    .email p {
        display: flex;
        flex-direction: row;
        width: 100px;
        align-items: center;
    }

    .footer-distributed .footer-right {
        /* display: inline-block;
      width: 35px;
      height: 35px;
      background-color: #33383b;
      border-radius: 2px;
      font-size: 20px;
      color: #ffffff;
      text-align: center;
      line-height: 35px;
      margin-left: 3px;
      transition: all 0.25s;
      margin-right: 25px; */
        margin-right: 150px;
        color: white;
    }

    .footer-distributed .footer-right {
        padding-bottom: 0px;
    }

    .footer-distributed .footer-right .con-detail {
        padding: 3px 0;
    }

    .footer-distributed .footer-right .con-detail {
        padding: 3px 0;
    }

    .footer-distributed .footer-right i {
        margin-right: 7px;
    }

    .footer-distributed .footer-right a:hover {
        transform: scale(1.1);
        -webkit-transform: scale(1.1);
    }

    .footer-distributed p.footer-links a:hover {
        text-decoration: underline;
    }

    /* Media Queries */

    @media (max-width: 600px) {

        .footer-distributed .footer-left {
            text-align: center;
        }

        .footer-distributed .footer-right {
            text-align: left;
            margin-left: 0px
        }

        .footer-distributed .footer-right {
            float: none;
            margin: 0 -20px;
        }

        .footer-distributed .footer-left p.footer-links {
            line-height: 1.8;
        }
    }

    @keyframes color-change {
        0% {
            color: red;
        }

        20% {
            color: rgb(255, 127, 8);
        }

        40% {
            color: rgb(243, 255, 82);
        }

        60% {
            color: rgb(97, 255, 82);
        }

        80% {
            color: rgb(82, 235, 255);
        }

        100% {
            color: rgb(255, 82, 218);
        }
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
    crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap"
    rel="stylesheet" />

<footer class="footer-distributed" style="z-index: 1;">
    <div class="footer-right">
        <h4 style="font-size: 18px;">Contact</h4>

        <p><i class="con-detail fas fa-phone-alt"></i>9130632505</p>

        <p><i class="con-detail fas fa-mobile-alt"></i>7045531929</p>

        <div class="con-detail email">
            <p><i class="fas fa-envelope"></i>pce@mes.com</p>
        </div>
    </div>

    <div class="footer-left">
        <p class="footer-links">
            <a class="link-1" href="{% url 'blogslist' %}">Blog</a>
            <a href="{% url 'eventslist' %}">Events</a>
            <a href="{% url 'committee:committee' %}">Committee</a>
            <a href="{% url 'eventslist' %}" style="animation: color-change 1s infinite;">Home</a>
        </p>

        <p>
            Made by students of Pillai College of Engineering, New Panvel &copy; 2021
        </p>
        <br />
        <p>
            Visit Pillai College's official website
            <a href="https://www.pce.ac.in/" style="text-decoration: none; color: white; font-weight: 600;">here</a>
        </p>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

eventapp/templates/snippets/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger" style="width: fit-content;">
            <strong>{{ error }}</strong>
        </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" style="width: fit-content;">
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
{% endif %}

eventapp/templates/snippets/header.html
{% load static %}

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    #nav{
        background: #4D189B;
		background: -webkit-linear-gradient(top left, #4D189B, #C174E8);
		background: -moz-linear-gradient(top left, #4D189B, #C174E8);
		background: linear-gradient(to bottom right, #4D189B, #C174E8);
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: Montserrat, sans-serif;
    }

    .nav-bar {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-around;
        height: 60px;


    }

    @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
    }

    .container {
        max-width: 1100px;
    }

    .pricing-header {
        max-width: 700px;
    }

    .card-deck .card {
        min-width: 220px;
    }

    .title {
        display: flex;
        flex-direction: row;
        align-items: center;
    }

    .title .name p a {
        font-weight: 600;
        color: white;
        padding-left: 20px;
        font-size: 25px;
    }

    .logo img {
        width: 40px;
        height: 40px;
    }

    .search-bar {
        display: flex;
        flex-direction: row;
        max-width: 350px;
        width: 100%;
        margin-left: 30px;
    }

    .form-control:focus {
        outline: none;
    }

    .search-bar input {
        border: none;
        border-radius: 25px;
        width: 350px;
        height: 30px;
    }

    .fa-search {
        position: absolute;
        padding-top: 8px;
        padding-left: 20px;
        color: white;
        font-size: 18px;
    }

    .nav-item .name a {
        font-weight: 500;
        color: white;
        padding-left: 20px;
        font-size: 20px;
    }

    .nav-link {
        color: white;
    }

    input {
        padding-left: 10px;
    }
    
    #nv:focus{
       background-color:lightcyan;
    }


    @keyframes color-change {
        0% {
            color: red;
        }

        20% {
            color: rgb(255, 127, 8);
        }

        40% {
            color: rgb(243, 255, 82);
        }

        60% {
            color: rgb(97, 255, 82);
        }

        80% {
            color: rgb(82, 235, 255);
        }

        100% {
            color: rgb(255, 82, 218);
        }
    }
</style>
<nav class="navbar navbar-expand-md fixed-top" id="nav">
    <div class="title">
        <div class="logo"><img src="{% static 'img/megaphone.png' %}"></img></div>
        <div class="name">
            <p style="margin-bottom: 0;">
                <a href="{% url 'eventslist' %}" style="animation: color-change 1s infinite;">
                    EventAdda
                </a>
            </p>
        </div>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <form class="form-inline my-2 my-lg-0" method=" GET" action=".">
            <div class="search-bar">
                <input class="form-control mr-sm-2" type="text" name="title" id="title"
                    placeholder="Search title" aria-label="Search">
            </div>
        </form>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <div class="name">
                    <a class="nav-link" href="{% url 'eventslist' %}">Events<span class="sr-only">(current)</span></a>
                </div>
            </li>
            <li class="nav-item active">
                <div class="name">
                    <a class="nav-link" href="{% url 'blogslist' %}">Blog<span class="sr-only">(current)</span></a>
                </div>
            </li>
            <li class="nav-item active">
                <div class="name">
                    <a class="nav-link" href="{% url 'committee:committee' %}">Committee<span class="sr-only">(current)</span></a>
                </div>
            </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <div class="name">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Actions</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" id="nv" style="font-weight: 150; color: #9101FF;"
                            href="{% url 'create-event' %}">Post Event</a>
                        <a class="dropdown-item" id="nv" style="font-weight: 150; color: #9101FF;"
                            href="{% url 'create-blog' %}">Post Blog</a>
                    </div>
                </div>
            </li>
            {% endif %}
        </ul>

        <nav class="my-2 my-md-0 mr-md-3">
            {% if request.user.is_authenticated %}
            <a class="p-2 text-white" href="{% url 'account' %}">Your Account</a>
            <a class="btn btn-outline" style="background: white;" href="{% url 'logout' %}">logout</a>
            {% else %}

            <!--<a class="p-2 text-white" href="#">Register</a>-->
            <a class="btn btn-outline" style="background: white;" href="{% url 'login' %}">Login</a>
            {% endif %}
        </nav>
    </div>
</nav>